apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-server
  
  template:
    metadata:
      name: frontend-server
      labels:
        app: frontend-server
    spec:
      containers:
        - name: frontend-server
          image: wparth/frontend-server:latest
          imagePullPolicy: Always
          
          resources:
            requests:
              cpu: "0.5"
              memory: "0.5G"
            limits:
              cpu: "1"
              memory: "1G"

          startupProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 3
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 3
            failureThreshold: 2

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nodegroup-name
                  operator: In
                  values:
                    - "web"
      tolerations:
        - key: "nodegroup-name"
          operator: "Equal"
          value: "web"
          effect: "NoSchedule"