apiVersion: v1
kind: Service
metadata:
  name: frontend-server
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: frontend-server
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80