---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-role
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods"]
  verbs: ["get", "create", "update", "patch", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-role
subjects:
- kind: ServiceAccount
  name: docker-cred-acc
  namespace: cicd-space
