apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-nodejs-app
  namespace: cicd-space
spec:
  inputs:
    params:
      - name: DEPLOY_SPACE
        description: The namespace where you deploy the app
        default: 'default'
        type: string
  steps:
    - name: test-image
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "get"
        - "pod"
        - "-n"
        - "$(inputs.params.DEPLOY_SPACE)"
