apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: weather-app-git
  namespace: cicd-space
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/parthw/weather-app
